// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS5SLioVkDSUpaapNskUT_0cDMAVsIsfw',
    appId: '1:167779968793:web:3f691c613ecc6283b1c788',
    messagingSenderId: '167779968793',
    projectId: 'fasum-faae5',
    authDomain: 'fasum-faae5.firebaseapp.com',
    storageBucket: 'fasum-faae5.appspot.com',
    measurementId: 'G-HFMRY4KPFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWcOYqnGuHlwKRgAPshWCX2zFwpfd2rus',
    appId: '1:167779968793:android:7c54253cfd05495db1c788',
    messagingSenderId: '167779968793',
    projectId: 'fasum-faae5',
    storageBucket: 'fasum-faae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWkTmhNmfQZl6Jdb00Zepr9yu0R3xmTJA',
    appId: '1:167779968793:ios:cbed197c41b9be56b1c788',
    messagingSenderId: '167779968793',
    projectId: 'fasum-faae5',
    storageBucket: 'fasum-faae5.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWkTmhNmfQZl6Jdb00Zepr9yu0R3xmTJA',
    appId: '1:167779968793:ios:fd76e2bbdbc8509ab1c788',
    messagingSenderId: '167779968793',
    projectId: 'fasum-faae5',
    storageBucket: 'fasum-faae5.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
